# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HuzzahPay Merchant' do
use_frameworks!

# Pods for HuzzahPay Merchant
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Auth'

end
